base_url = "https://vishaltr1012.github.io"
title = "Vishal TR Photography"
description = "Photography by Vishal TR"
compile_sass = true
generate_feeds = false

[markdown]
highlight_code = false

[extra]
author = "Vishal TR"
